# Generated by Django 5.2.4 on 2026-01-08 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('academic_history', models.JSONField(default=list)),
                ('english_proficiency', models.CharField(blank=True, max_length=50)),
                ('english_score', models.CharField(blank=True, max_length=20)),
                ('additional_qualifications', models.TextField(blank=True)),
                ('program', models.CharField(choices=[('business', 'Business Administration (MBA)'), ('computer-science', 'Computer Science'), ('data-science', 'Data Science'), ('engineering', 'Engineering'), ('health-sciences', 'Health Sciences'), ('psychology', 'Psychology'), ('economics', 'Economics'), ('law', 'Law'), ('arts', 'Arts & Humanities')], max_length=50)),
                ('degree_level', models.CharField(choices=[('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD/Doctorate')], max_length=20)),
                ('study_mode', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('online', 'Online'), ('hybrid', 'Hybrid')], max_length=20)),
                ('intake', models.CharField(choices=[('fall-2025', 'Fall 2025'), ('spring-2026', 'Spring 2026'), ('fall-2026', 'Fall 2026')], max_length=20)),
                ('scholarship', models.BooleanField(default=False)),
                ('referral_source', models.CharField(blank=True, max_length=100)),
                ('documents_uploaded', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted', models.BooleanField(default=False)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Course Application',
                'verbose_name_plural': 'Course Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
