# Generated by Django 5.2.4 on 2026-01-08 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0002_courseapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('IN', 'India'), ('CN', 'China'), ('NG', 'Nigeria'), ('BR', 'Brazil'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-binary'), ('prefer-not-to-say', 'Prefer not to say')], max_length=50),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('search-engine', 'Search Engine (Google, etc.)'), ('social-media', 'Social Media'), ('friend-family', 'Friend or Family'), ('education-fair', 'Education Fair'), ('school-counselor', 'School Counselor'), ('alumni', 'MIU Alumni'), ('other', 'Other')], max_length=100),
        ),
        migrations.CreateModel(
            name='CourseApplicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='applications/additional/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_files', to='eduweb.courseapplication')),
            ],
        ),
    ]
