# Generated by Django 5.0.1 on 2026-01-17 23:09

import datetime
import django.core.validators
import django.db.models.deletion
import eduweb.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0005_courseapplication_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseapplicationfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Application File', 'verbose_name_plural': 'Application Files'},
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='decision_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed'), ('decision_made', 'Decision Made')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='courseapplicationfile',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseapplicationfile',
            name='file_type',
            field=models.CharField(choices=[('transcripts', 'Transcripts'), ('english_proficiency', 'English Proficiency Certificate'), ('personal_statement', 'Personal Statement'), ('cv', 'CV/Resume'), ('other', 'Other Document')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='courseapplicationfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 17, 23, 9, 55, 572206, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('website', 'University Website'), ('search-engine', 'Search Engine (Google, etc.)'), ('social-media', 'Social Media'), ('friend-family', 'Friend or Family'), ('education-fair', 'Education Fair'), ('school-counselor', 'School Counselor'), ('alumni', 'MIU Alumni'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='eduweb.courseapplication'),
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='file',
            field=models.FileField(upload_to=eduweb.models.application_file_upload_path),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pending_payment', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduweb.application')),
            ],
        ),
    ]
