# Generated by Django 5.0.1 on 2026-01-17 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0006_alter_courseapplicationfile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 17, 23, 11, 14, 81980, tzinfo=datetime.timezone.utc)),
        ),
    ]
