# Generated by Django 6.0.2 on 2026-03-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_academic_subtitle',
            field=models.TextField(blank=True, default='Our academic structure is designed to foster interdisciplinary collaboration and innovation across diverse fields.', help_text="Subtitle paragraph under 'Academic Excellence' heading"),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_accreditation_subtitle',
            field=models.TextField(blank=True, default='Recognized excellence in higher education with global accreditation and rankings.', help_text="Subtitle paragraph under 'Accreditation & Rankings' heading"),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_cta_heading',
            field=models.CharField(blank=True, default='Ready to Start Your Journey?', help_text='CTA heading on about page (school_short_name is appended in the template)', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_cta_text',
            field=models.TextField(blank=True, default='Join our global community of learners and innovators. Your future starts here.', help_text='CTA subtitle paragraph on about page'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_current_year',
            field=models.CharField(blank=True, default='2025', help_text="The 'Today' year label at the end of the history timeline", max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_facilities_subtitle',
            field=models.TextField(blank=True, default='State-of-the-art facilities designed to enhance learning experiences and campus life.', help_text="Subtitle paragraph under 'Campus & Facilities' heading"),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_global_partnerships_text',
            field=models.TextField(blank=True, help_text="Paragraph under 'Global Campuses & Partnerships'. Leave blank to use the auto-generated text with school_short_name and about_partner_institutions."),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_hero_badge',
            field=models.CharField(blank=True, default='Discover Our Story', help_text='Small pill badge text in the about page hero (above the h1)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_history_image',
            field=models.ImageField(blank=True, help_text='Photo beside the history timeline (replaces Unsplash placeholder when uploaded)', null=True, upload_to='about/history/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_leadership_subtitle',
            field=models.TextField(blank=True, default='Guided by experienced leaders committed to educational excellence and innovation.', help_text="Subtitle paragraph under 'Leadership & Governance' heading"),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_section_heading',
            field=models.CharField(blank=True, default='Global Outlook, Local Impact', help_text='h3 subheading inside the Who We Are two-column layout', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_support_subtitle',
            field=models.TextField(blank=True, default='Comprehensive support services for holistic student development and success.', help_text="Subtitle paragraph under 'Student Support & Services' heading"),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='campus_airport_info',
            field=models.TextField(blank=True, default='25 minutes from International Airport. Taxi/Uber available. Airport shuttle every 30 mins.', help_text='Directions from airport shown below campus map'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='campus_parking_info',
            field=models.TextField(blank=True, default='Visitor parking available in Lot A. Daily parking pass: $10. Free on weekends.', help_text='Parking details shown below campus map'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='campus_transit_info',
            field=models.TextField(blank=True, default='Take Metro Line 1 to University Station. Campus is a 5-minute walk from exit B.', help_text='Public transit directions shown below campus map'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_labs_desc',
            field=models.TextField(blank=True, default='Advanced research facilities for biotechnology, AI, engineering, and data science.', help_text='Research labs facility card description'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_labs_image',
            field=models.ImageField(blank=True, help_text='Research labs card photo (replaces Unsplash placeholder when uploaded)', null=True, upload_to='about/facilities/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_labs_name',
            field=models.CharField(blank=True, default='Research Laboratories', help_text='Research labs facility card title', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_labs_note',
            field=models.CharField(blank=True, default='15 interdisciplinary research centers', help_text='Small footer note on labs card (shown with flask icon)', max_length=150),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_library_desc',
            field=models.TextField(blank=True, default='500,000+ physical and digital resources, 24/7 access, and collaborative study spaces.', help_text='Library facility card description'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_library_image',
            field=models.ImageField(blank=True, help_text='Library card photo (replaces Unsplash placeholder when uploaded)', null=True, upload_to='about/facilities/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_library_name',
            field=models.CharField(blank=True, default='Modern Library', help_text='Library facility card title', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_library_note',
            field=models.CharField(blank=True, default='Open 24/7 during exam periods', help_text='Small footer note on library card (shown with clock icon)', max_length=150),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_recreation_desc',
            field=models.TextField(blank=True, default='Olympic-sized pool, fitness center, basketball courts, and wellness programs.', help_text='Recreation center facility card description'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_recreation_image',
            field=models.ImageField(blank=True, help_text='Recreation center card photo (replaces Unsplash placeholder when uploaded)', null=True, upload_to='about/facilities/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_recreation_name',
            field=models.CharField(blank=True, default='Recreation Center', help_text='Recreation center facility card title', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facility_recreation_note',
            field=models.CharField(blank=True, default='Free for all students and staff', help_text='Small footer note on recreation card (shown with heart icon)', max_length=150),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='history_founding_text',
            field=models.TextField(blank=True, default='MIU is established with a vision to provide accessible, quality higher education through innovative delivery methods.', help_text='Body text for the Founding milestone card (1st timeline entry)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='history_milestone_2_text',
            field=models.TextField(blank=True, default='Launch of our first fully online degree programs, pioneering digital education.', help_text='Body text for 2nd history milestone'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='history_milestone_2_title',
            field=models.CharField(blank=True, default='Digital Transformation', help_text='Title for 2nd history milestone', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='history_milestone_2_year',
            field=models.CharField(blank=True, default='2005', help_text='Year label for 2nd history milestone', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='history_milestone_3_text',
            field=models.TextField(blank=True, default='Establishment of international campuses in Europe and Asia, serving students from over 80 countries.', help_text='Body text for 3rd history milestone'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='history_milestone_3_title',
            field=models.CharField(blank=True, default='Global Expansion', help_text='Title for 3rd history milestone', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='history_milestone_3_year',
            field=models.CharField(blank=True, default='2015', help_text='Year label for 3rd history milestone', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='history_milestone_4_text',
            field=models.TextField(blank=True, default='Opening of the MIU Innovation Center, fostering research and entrepreneurship.', help_text='Body text for 4th history milestone'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='history_milestone_4_title',
            field=models.CharField(blank=True, default='Innovation Hub', help_text='Title for 4th history milestone', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='history_milestone_4_year',
            field=models.CharField(blank=True, default='2020', help_text='Year label for 4th history milestone', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='index_programs_subtitle',
            field=models.TextField(blank=True, default='Choose from our extensive range of accredited programs designed for the global workforce.', help_text="Subtitle under 'Popular Programs' heading on index page"),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='intl_support_services',
            field=models.JSONField(blank=True, default=list, help_text='International Student Support bullet list. Each item is a string. Example: ["Visa and immigration assistance", "Airport pickup and arrival services", "Cross-cultural training programs", "International student advisors"]'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='support_academic_items',
            field=models.JSONField(blank=True, default=list, help_text='Academic Support card bullet list. Each item is a string. Example: ["Tutoring centers for all subjects", "Writing and research assistance", "Academic advising and mentoring", "Technology support and digital literacy"]'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='support_career_items',
            field=models.JSONField(blank=True, default=list, help_text='Career Services card bullet list. Each item is a string. Example: ["Career counseling and job search strategies", "Internship and co-op placement", "Networking events and career fairs", "Resume and interview preparation"]'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='support_health_items',
            field=models.JSONField(blank=True, default=list, help_text='Health & Wellbeing card bullet list. Each item is a string. Example: ["24/7 health center with medical professionals", "Counseling and mental health services", "Nutritional counseling and wellness programs", "Disability support and accessibility services"]'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='virtual_tour_url',
            field=models.TextField(blank=True, help_text="Full <iframe> embed code for the virtual campus tour video (YouTube, Vimeo, etc.). When filled, an embedded video player is shown instead of the static 'Take Virtual Campus Tour' button."),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_exchange_programs',
            field=models.CharField(blank=True, default='40+', help_text="Exchange programs count e.g. '40+'", max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_intro_1',
            field=models.TextField(blank=True, help_text='Who We Are section subtitle AND first body paragraph on about page'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_intro_2',
            field=models.TextField(blank=True, help_text='Second body paragraph in Who We Are section'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_languages_spoken',
            field=models.CharField(blank=True, default='15+', help_text="Languages spoken count e.g. '15+'", max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_partner_institutions',
            field=models.CharField(blank=True, default='200+', help_text="Partner institutions count e.g. '200+'", max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_years_founded',
            field=models.CharField(blank=True, default='1995', help_text='Founding year — appears in timeline, history subtitle, and international section', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='accreditation_1',
            field=models.CharField(blank=True, help_text='Regional Accreditation card text', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='accreditation_2',
            field=models.CharField(blank=True, help_text='Global Rankings card text', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='accreditation_3',
            field=models.CharField(blank=True, help_text='Program Accreditation card text', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='accreditation_4',
            field=models.CharField(blank=True, help_text='Quality Recognition card text', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='address_nigeria',
            field=models.TextField(blank=True, help_text='Nigeria campus address'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='address_usa',
            field=models.TextField(blank=True, help_text='US campus address'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='campus_map_address',
            field=models.CharField(blank=True, help_text="Address shown on map overlay card and used for 'Get Directions' link", max_length=300),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='campus_map_embed_url',
            field=models.TextField(blank=True, help_text='Full <iframe> embed code from Google Maps for campus map section'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='copyright_year',
            field=models.CharField(blank=True, default='2025', help_text="Year shown in footer copyright line e.g. '2025'", max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='core_values_text',
            field=models.JSONField(blank=True, help_text='Our Values — list of strings. Example: ["Excellence in Education", "Diversity & Inclusion", "Innovation & Creativity", "Global Citizenship"]', null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_badge_text',
            field=models.CharField(blank=True, default='Melchisedec International University', help_text='Small pill badge above hero heading on index page', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_heading',
            field=models.CharField(blank=True, default='Welcome to MIU', help_text='Main h1 first line in index hero', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_subheading',
            field=models.CharField(blank=True, default='Global Institution of Excellence in Learning and Academics', help_text='Paragraph subtitle below hero heading', max_length=300),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_tagline',
            field=models.CharField(blank=True, default='The Best Learning Institution', help_text='Gold uppercase subtitle line below badge in index hero', max_length=300),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='index_about_para_1',
            field=models.TextField(blank=True, help_text="First paragraph in index about section (below 'About MIU' heading)"),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='index_about_para_2',
            field=models.TextField(blank=True, help_text='Second paragraph / mission text in index about section'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Dark-background variant of the logo', null=True, upload_to='site/logos/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description — also populates og:description and twitter:description'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='SEO meta keywords (comma separated)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='mission_text',
            field=models.TextField(blank=True, help_text='Our Mission card body text'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='office_hours_saturday',
            field=models.CharField(blank=True, help_text='e.g. Saturday: 9:00 AM – 1:00 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='office_hours_weekday',
            field=models.CharField(blank=True, help_text='e.g. Monday – Friday: 8:00 AM – 6:00 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Default Open Graph share image (1200×630 px recommended)', null=True, upload_to='site/og/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone_ng_primary',
            field=models.CharField(blank=True, help_text='Primary Nigeria phone number', max_length=30),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='phone_ng_secondary',
            field=models.CharField(blank=True, help_text='Secondary Nigeria phone number', max_length=30),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='promo_video_url',
            field=models.TextField(blank=True, help_text='Full <iframe> embed code from YouTube/Vimeo for promo video'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_countries_count',
            field=models.IntegerField(blank=True, default=120, help_text='Countries Represented animated counter'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_countries_label',
            field=models.CharField(blank=True, default='120+', help_text="Countries Represented card value e.g. '120+'", max_length=30),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_employment_label',
            field=models.CharField(blank=True, default='95%', help_text="Graduate Employment card value e.g. '95%'", max_length=30),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_employment_rate',
            field=models.IntegerField(blank=True, default=95, help_text='Graduate Employment % animated counter'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_programs_count',
            field=models.IntegerField(blank=True, default=50, help_text='Academic Programs animated counter'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_programs_label',
            field=models.CharField(blank=True, default='50+', help_text="Academic Programs card value e.g. '50+'", max_length=30),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_students',
            field=models.CharField(blank=True, default='25,000+', help_text="Students Worldwide card value e.g. '25,000+'", max_length=30),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_years_count',
            field=models.IntegerField(blank=True, default=30, help_text='Years of Excellence animated counter'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short tagline used in about.html hero subtitle and index about section', max_length=300),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='vision_text',
            field=models.TextField(blank=True, help_text='Our Vision card body text'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number — digits only e.g. 15551234567', max_length=30),
        ),
    ]
