# Generated by Django 5.2.4 on 2026-02-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('payment_complete', 'Payment Complete'), ('under_review', 'Under Review'), ('documents_uploaded', 'Documents Uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=30),
        ),
    ]
