# Generated by Django 6.0.2 on 2026-02-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lmscourse',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='price',
        ),
    ]
