# Generated by Django 5.0.1 on 2026-07-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0002_alter_staffpermissionsmatrix_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='gallery_image_1',
            field=models.ImageField(blank=True, help_text='Gallery image 1 (max 3MB)', null=True, upload_to='faculties/gallery/images/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='gallery_image_2',
            field=models.ImageField(blank=True, help_text='Gallery image 2 (max 3MB)', null=True, upload_to='faculties/gallery/images/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='gallery_image_3',
            field=models.ImageField(blank=True, help_text='Gallery image 3 (max 3MB)', null=True, upload_to='faculties/gallery/images/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='gallery_video',
            field=models.FileField(blank=True, help_text='Gallery video (shown first in carousel if present)', null=True, upload_to='faculties/gallery/videos/'),
        ),
        migrations.AddField(
            model_name='program',
            name='gallery_image_1',
            field=models.ImageField(blank=True, help_text='Gallery image 1 (max 3MB)', null=True, upload_to='programs/gallery/images/'),
        ),
        migrations.AddField(
            model_name='program',
            name='gallery_image_2',
            field=models.ImageField(blank=True, help_text='Gallery image 2 (max 3MB)', null=True, upload_to='programs/gallery/images/'),
        ),
        migrations.AddField(
            model_name='program',
            name='gallery_image_3',
            field=models.ImageField(blank=True, help_text='Gallery image 3 (max 3MB)', null=True, upload_to='programs/gallery/images/'),
        ),
        migrations.AddField(
            model_name='program',
            name='gallery_video',
            field=models.FileField(blank=True, help_text='Gallery video (shown first in carousel if present)', null=True, upload_to='programs/gallery/videos/'),
        ),
    ]
