# Generated by Django 5.2.4 on 2026-02-09 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0002_alter_courseapplication_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('filter_type', models.CharField(choices=[('all_users', 'All Users'), ('role', 'By User Role'), ('faculty', 'By Faculty'), ('course', 'By Course (Admission)'), ('lms_course', 'By LMS Course'), ('application_status', 'By Application Status'), ('enrollment_status', 'By Enrollment Status')], max_length=30)),
                ('filter_values', models.JSONField(default=dict, help_text='Stores selected filters')),
                ('recipient_count', models.IntegerField(default=0)),
                ('recipient_emails', models.JSONField(default=list, help_text='List of recipient emails')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast Message',
                'verbose_name_plural': 'Broadcast Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='eduweb_broa_status_f2cbf4_idx'), models.Index(fields=['filter_type'], name='eduweb_broa_filter__f8a04c_idx')],
            },
        ),
    ]
