# Generated by Django 6.0.2 on 2026-03-24 13:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0002_libraryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmscourse',
            name='certificate_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fee charged to the student to receive their certificate', max_digits=10),
        ),
    ]
