# Generated by Django 6.0.2 on 2026-03-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0002_siteconfig_about_academic_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(help_text="e.g. 'MBA Graduate, 2023'", max_length=150)),
                ('avatar', models.ImageField(blank=True, help_text='Author photo. If left blank, initials will be shown instead.', null=True, upload_to='testimonials/avatars/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_hero_image',
            field=models.ImageField(blank=True, help_text='Optional background image for the about page hero section. When set, overlays the gradient with a photo. Leave blank to keep gradient only.', null=True, upload_to='about/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='admissions_financial_aid',
            field=models.JSONField(blank=True, default=list, help_text='Financial Aid tab cards. List of objects with \'title\', \'icon\', \'description\', and optional \'items\' list. Example: [{"title": "Scholarships", "icon": "award", "description": "Merit-based, up to 100% tuition coverage.", "items": ["Presidential: Full tuition", "Dean\'s Award: 50%", "Excellence Grant: 25%"]}, {"title": "Grants", "icon": "gift", "description": "Need-based assistance that never requires repayment.", "items": []}, {"title": "Student Loans", "icon": "landmark", "description": "Low-interest government & private loan programs.", "items": []}]'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='admissions_key_dates',
            field=models.JSONField(blank=True, default=list, help_text='Key Dates tab cards. List of objects with \'label\', \'start\', \'early_deadline\', \'final_deadline\', \'badge\' (optional text e.g. \'Priority\'), and \'note\' (optional). Example: [{"label": "Fall 2025", "start": "September 2025", "early_deadline": "Mar 15, 2025", "final_deadline": "Jun 15, 2025", "badge": "Priority", "note": ""}, {"label": "Spring 2026", "start": "January 2026", "early_deadline": "Sep 1, 2025", "final_deadline": "Nov 1, 2025", "badge": "", "note": ""}, {"label": "Scholarship Priority", "start": "For maximum consideration", "early_deadline": "", "final_deadline": "Mar 31, 2025", "badge": "Funding", "note": "Apply early for the best scholarship consideration."}]'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='admissions_key_dates_footer_note',
            field=models.CharField(blank=True, default='Apply early for the best scholarship consideration.', help_text='Footer note shown at the bottom of the Key Dates panel', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='admissions_process_steps',
            field=models.JSONField(blank=True, default=list, help_text='Application Process tab steps. List of objects with \'title\' and \'description\'. Example: [{"title": "Submit Application", "description": "Complete our online form with academic records."}, {"title": "Academic Review", "description": "Admissions team evaluates your credentials within 2–3 weeks."}, {"title": "Interview Stage", "description": "Virtual or in-person interview for select programs."}, {"title": "Decision & Enrollment", "description": "Receive your decision and begin enrollment."}]'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='admissions_section_subtitle',
            field=models.CharField(blank=True, default='Quality education made accessible — simple process, real funding options.', help_text='Subtitle paragraph under the Admissions section heading', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image_1',
            field=models.ImageField(blank=True, help_text='Hero background image — slide 1 (first active slide shown on load)', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image_1_alt',
            field=models.CharField(blank=True, default='Students collaborating on campus', help_text='Accessibility alt/aria-label for slide 1', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image_1_duration',
            field=models.PositiveSmallIntegerField(default=6, help_text='How many seconds slide 1 stays visible before advancing'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image_2',
            field=models.ImageField(blank=True, help_text='Hero background image — slide 2', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image_2_alt',
            field=models.CharField(blank=True, default='Graduates celebrating commencement', help_text='Accessibility alt/aria-label for slide 2', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image_2_duration',
            field=models.PositiveSmallIntegerField(default=6, help_text='How many seconds slide 2 stays visible'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image_3',
            field=models.ImageField(blank=True, help_text='Hero background image — slide 3', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image_3_alt',
            field=models.CharField(blank=True, default='Students using technology in class', help_text='Accessibility alt/aria-label for slide 3', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image_3_duration',
            field=models.PositiveSmallIntegerField(default=6, help_text='How many seconds slide 3 stays visible'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_video_duration',
            field=models.PositiveSmallIntegerField(default=15, help_text='How many seconds the video slide stays before advancing (if not autoplaying)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_video_poster',
            field=models.ImageField(blank=True, help_text='Poster/thumbnail image shown while the video loads', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='Direct .mp4 URL for a hero background video (plays muted/looped). When filled this becomes the first hero slide. Leave blank for images only.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='show_about_section',
            field=models.BooleanField(default=True, help_text='Show the About MIU section'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='show_admissions_section',
            field=models.BooleanField(default=True, help_text='Show the Admissions & Financial Aid section'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='show_campus_map_section',
            field=models.BooleanField(default=True, help_text='Show the Find Our Campus / map section'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='show_contact_section',
            field=models.BooleanField(default=True, help_text='Show the Contact form & info section'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='show_faculties_section',
            field=models.BooleanField(default=True, help_text='Show the Academics & Faculties section'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='show_programs_section',
            field=models.BooleanField(default=True, help_text='Show the Popular Programs section'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='show_stats_section',
            field=models.BooleanField(default=True, help_text='Show the 4 stat cards section below the hero'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='show_testimonials_section',
            field=models.BooleanField(default=True, help_text='Show the Testimonials section (also requires at least one active Testimonial record)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='theme_color',
            field=models.CharField(blank=True, default='#840384', help_text="Browser theme-color meta tag hex value e.g. '#840384'", max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_accreditation_subtitle',
            field=models.TextField(blank=True, default='Recognized excellence in higher education with global accreditation and rankings.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_cta_heading',
            field=models.CharField(blank=True, default='Ready to Start Your Journey?', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_cta_text',
            field=models.TextField(blank=True, default='Join our global community of learners and innovators. Your future starts here.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_exchange_programs',
            field=models.CharField(blank=True, default='40+', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_facilities_subtitle',
            field=models.TextField(blank=True, default='State-of-the-art facilities designed to enhance learning experiences and campus life.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_global_partnerships_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_hero_badge',
            field=models.CharField(blank=True, default='Discover Our Story', help_text='Small pill badge text in the about page hero', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_history_image',
            field=models.ImageField(blank=True, help_text='Photo beside the history timeline', null=True, upload_to='about/history/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_languages_spoken',
            field=models.CharField(blank=True, default='15+', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_leadership_subtitle',
            field=models.TextField(blank=True, default='Guided by experienced leaders committed to educational excellence and innovation.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_partner_institutions',
            field=models.CharField(blank=True, default='200+', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='about_support_subtitle',
            field=models.TextField(blank=True, default='Comprehensive support services for holistic student development and success.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='campus_map_address',
            field=models.CharField(blank=True, help_text="Address shown on the map overlay card and used for the 'Get Directions' link", max_length=300),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='campus_map_embed_url',
            field=models.TextField(blank=True, help_text='Full <iframe> embed code from Google Maps for the campus map section'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_labs_desc',
            field=models.TextField(blank=True, default='Advanced research facilities for biotechnology, AI, engineering, and data science.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_labs_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/facilities/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_labs_name',
            field=models.CharField(blank=True, default='Research Laboratories', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_labs_note',
            field=models.CharField(blank=True, default='15 interdisciplinary research centers', max_length=150),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_library_desc',
            field=models.TextField(blank=True, default='500,000+ physical and digital resources, 24/7 access, and collaborative study spaces.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_library_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/facilities/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_library_name',
            field=models.CharField(blank=True, default='Modern Library', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_library_note',
            field=models.CharField(blank=True, default='Open 24/7 during exam periods', max_length=150),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_recreation_desc',
            field=models.TextField(blank=True, default='Olympic-sized pool, fitness center, basketball courts, and wellness programs.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_recreation_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/facilities/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_recreation_name',
            field=models.CharField(blank=True, default='Recreation Center', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facility_recreation_note',
            field=models.CharField(blank=True, default='Free for all students and staff', max_length=150),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_badge_text',
            field=models.CharField(blank=True, default='Melchisedec International University', help_text='Small pill badge above hero heading', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_heading',
            field=models.CharField(blank=True, default='Welcome to MIU', help_text='Main h1 first line', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_tagline',
            field=models.CharField(blank=True, default='The Best Learning Institution', help_text='Gold uppercase line below the badge', max_length=300),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='history_milestone_2_text',
            field=models.TextField(blank=True, default='Launch of our first fully online degree programs, pioneering digital education.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='history_milestone_2_title',
            field=models.CharField(blank=True, default='Digital Transformation', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='history_milestone_2_year',
            field=models.CharField(blank=True, default='2005', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='history_milestone_3_text',
            field=models.TextField(blank=True, default='Establishment of international campuses in Europe and Asia, serving students from over 80 countries.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='history_milestone_3_title',
            field=models.CharField(blank=True, default='Global Expansion', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='history_milestone_3_year',
            field=models.CharField(blank=True, default='2015', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='history_milestone_4_text',
            field=models.TextField(blank=True, default='Opening of the MIU Innovation Center, fostering research and entrepreneurship.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='history_milestone_4_title',
            field=models.CharField(blank=True, default='Innovation Hub', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='history_milestone_4_year',
            field=models.CharField(blank=True, default='2020', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='index_about_para_1',
            field=models.TextField(blank=True, help_text='First paragraph in the index About section'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='index_about_para_2',
            field=models.TextField(blank=True, help_text='Second paragraph in the index About section'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='intl_support_services',
            field=models.JSONField(blank=True, default=list, help_text='International Student Support bullet list. Each item is a string. Example: ["Visa and immigration assistance", "Airport pickup and arrival services"]'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Dark-background variant of the logo (used on dark nav/footer)', null=True, upload_to='site/logos/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='office_hours_saturday',
            field=models.CharField(blank=True, help_text='e.g. 9:00 AM – 1:00 PM. Leave blank to hide Saturday row.', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='office_hours_weekday',
            field=models.CharField(blank=True, help_text='e.g. 8:00 AM – 6:00 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='promo_video_url',
            field=models.TextField(blank=True, help_text='Full <iframe> embed code from YouTube/Vimeo for the About section promo video'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_countries_label',
            field=models.CharField(blank=True, default='120+', help_text="Countries Represented value e.g. '120+'", max_length=30),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_employment_label',
            field=models.CharField(blank=True, default='95%', help_text="Graduate Employment value e.g. '95%'", max_length=30),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_programs_label',
            field=models.CharField(blank=True, default='50+', help_text="Academic Programs value e.g. '50+'", max_length=30),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='stat_students',
            field=models.CharField(blank=True, default='25,000+', help_text="Students Worldwide value e.g. '25,000+'", max_length=30),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='support_academic_items',
            field=models.JSONField(blank=True, default=list, help_text='Academic Support card bullet list. Each item is a string.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='support_career_items',
            field=models.JSONField(blank=True, default=list, help_text='Career Services card bullet list. Each item is a string.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='support_health_items',
            field=models.JSONField(blank=True, default=list, help_text='Health & Wellbeing card bullet list. Each item is a string.'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='virtual_tour_url',
            field=models.TextField(blank=True, help_text="Full <iframe> embed code for the virtual campus tour video. When filled, an embedded video player is shown instead of the static 'Take Virtual Campus Tour' button."),
        ),
    ]
