# Generated by Django 5.2.4 on 2026-01-29 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0002_courseapplication_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who submitted this message (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
