# Generated by Django 6.0.2 on 2026-02-27 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0002_remove_lmscourse_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='eduweb.lmscourse'),
        ),
    ]
