# Generated by Django 5.0.1 on 2026-01-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0003_contactmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='language_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter test score (e.g. 7.5 for IELTS, 95 for TOEFL)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='language_skill',
            field=models.CharField(blank=True, choices=[('toefl', 'TOEFL'), ('ielts', 'IELTS'), ('pte', 'PTE Academic'), ('duolingo', 'Duolingo English Test'), ('cambridge', 'Cambridge English'), ('none', 'None')], max_length=20, null=True),
        ),
    ]
