# Generated by Django 5.0.1 on 2026-07-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0003_faculty_gallery_image_1_faculty_gallery_image_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['created_at'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='avg_starting_salary',
        ),
        migrations.RemoveField(
            model_name='program',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='program',
            name='job_placement_rate',
        ),
    ]
