# Generated by Django 5.2.4 on 2026-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0003_broadcastmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
