# Generated by Django 6.0.2 on 2026-02-27 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0003_alter_discussion_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_messages', to=settings.AUTH_USER_MODEL)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='eduweb.studygroup')),
            ],
            options={
                'verbose_name': 'Study Group Message',
                'verbose_name_plural': 'Study Group Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['study_group', 'created_at'], name='eduweb_stud_study_g_92cb45_idx')],
            },
        ),
    ]
