# Generated by Django 5.0.1 on 2026-01-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0004_courseapplication_language_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='accept_privacy_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='accept_terms_conditions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
    ]
