# Generated by Django 5.0.1 on 2026-07-27 03:39, reordered by hand: add the
# CourseIntake fields and copy Program.application_fee onto every one of a
# program's intakes BEFORE the Program field is dropped, so no fee data is
# silently lost in the move.

from decimal import Decimal

from django.db import migrations, models


def copy_program_fee_to_intakes(apps, schema_editor):
    Program = apps.get_model('eduweb', 'Program')
    for program in Program.objects.exclude(application_fee=Decimal('0.00')):
        program.intakes.update(application_fee=program.application_fee)


def noop_reverse(apps, schema_editor):
    """Nothing to reverse into — Program.application_fee is dropped by the
    RemoveField that follows this migration; there's no column left to
    write back into on a reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0004_remove_program_display_order_and_marketing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseintake',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee to apply for this specific intake', max_digits=10),
        ),
        migrations.AddField(
            model_name='courseintake',
            name='application_start_date',
            field=models.DateField(blank=True, help_text='When applications open for this intake', null=True),
        ),
        migrations.RunPython(copy_program_fee_to_intakes, noop_reverse),
        migrations.RemoveField(
            model_name='program',
            name='application_fee',
        ),
    ]
