# Generated by Django 5.0.1 on 2026-03-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0004_studygroupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='emergency_contact_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='how_did_you_hear_other',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
