# Generated by Django 6.0.2 on 2026-03-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0004_remove_siteconfig_about_academic_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_1_alt',
            field=models.CharField(blank=True, default='Students collaborating on campus', help_text='Accessibility label for slide 1', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_1_duration',
            field=models.PositiveSmallIntegerField(default=6, help_text='Seconds slide 1 stays visible before advancing'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_1_image',
            field=models.ImageField(blank=True, help_text='Slide 1 background image', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_1_video',
            field=models.FileField(blank=True, help_text='Slide 1 background video (.mp4). Used instead of image if set.', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_2_alt',
            field=models.CharField(blank=True, default='Graduates celebrating commencement', help_text='Accessibility label for slide 2', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_2_duration',
            field=models.PositiveSmallIntegerField(default=6, help_text='Seconds slide 2 stays visible before advancing'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_2_image',
            field=models.ImageField(blank=True, help_text='Slide 2 background image', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_2_video',
            field=models.FileField(blank=True, help_text='Slide 2 background video (.mp4). Used instead of image if set.', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_3_alt',
            field=models.CharField(blank=True, default='Students using technology in class', help_text='Accessibility label for slide 3', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_3_duration',
            field=models.PositiveSmallIntegerField(default=6, help_text='Seconds slide 3 stays visible before advancing'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_3_image',
            field=models.ImageField(blank=True, help_text='Slide 3 background image', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_slide_3_video',
            field=models.FileField(blank=True, help_text='Slide 3 background video (.mp4). Used instead of image if set.', null=True, upload_to='site/hero/'),
        ),
    ]
