# Generated by Django 6.0.2 on 2026-03-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('grade', 'Grade'), ('announcement', 'Announcement'), ('message', 'Message'), ('certificate', 'Certificate'), ('payroll', 'Payroll'), ('account', 'Account'), ('system', 'System')], max_length=30),
        ),
    ]
