# Generated by Django 5.2.4 on 2026-02-09 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0004_broadcastmessage_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='admission_accepted',
            field=models.BooleanField(default=False, help_text='Student accepted the admission offer'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='admission_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Date when student accepted admission', null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='admission_number',
            field=models.CharField(blank=True, help_text='Unique admission number issued to student', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='department_approved',
            field=models.BooleanField(default=False, help_text='Department head approved the admission'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='department_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='department_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_approved_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
