# Generated by Django 5.0.1 on 2026-01-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0005_courseapplication_accept_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='scholarship',
            field=models.BooleanField(default=False),
        ),
    ]
