# Generated by Django 5.0.1 on 2026-03-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0005_courseapplication_emergency_contact_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, unique=True)),
                ('country_code', models.CharField(max_length=10, unique=True)),
                ('country_phonecode', models.CharField(max_length=10)),
            ],
        ),
    ]
