# Generated by Django 5.2.4 on 2026-02-10 05:47

import django.core.validators
import eduweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0005_courseapplication_admission_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Or upload video file (MP4, WebM, OGG, AVI, MOV)', null=True, upload_to=eduweb.models.get_video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'avi', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, or external video URL', null=True),
        ),
    ]
