# Generated by Django 6.0.2 on 2026-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
