# Generated by Django 5.2.4 on 2026-01-13 11:59

import django.db.models.deletion
import django.utils.timezone
import eduweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0005_courseapplication_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseapplicationfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Application File', 'verbose_name_plural': 'Application Files'},
        ),
        migrations.AddField(
            model_name='courseapplicationfile',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseapplicationfile',
            name='file_type',
            field=models.CharField(choices=[('transcripts', 'Transcripts'), ('english_proficiency', 'English Proficiency Certificate'), ('personal_statement', 'Personal Statement'), ('cv', 'CV/Resume'), ('other', 'Other Document')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='courseapplicationfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='eduweb.courseapplication'),
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='file',
            field=models.FileField(upload_to=eduweb.models.application_file_upload_path),
        ),
    ]
