# Generated by Django 5.0.1 on 2026-03-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0006_listofcountry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listofcountry',
            options={'ordering': ['country'], 'verbose_name': 'Country', 'verbose_name_plural': 'List of Countries'},
        ),
        migrations.AddField(
            model_name='listofcountry',
            name='nationality',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
