# Generated by Django 6.0.2 on 2026-03-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0006_alter_feepayment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
