# Generated by Django 5.2.4 on 2026-02-12 22:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0006_lesson_video_file_alter_lesson_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_reference', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Housing, transport, etc.', max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Performance bonuses', max_digits=10)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Income tax', max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Insurance, loans, etc.', max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cash', 'Cash'), ('mobile_money', 'Mobile Money')], default='bank_transfer', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('attachment_1', models.FileField(blank=True, help_text='Salary slip, contract, etc.', null=True, upload_to='payroll/attachments/%Y/%m/')),
                ('attachment_1_name', models.CharField(blank=True, default='', help_text='Display name for attachment 1', max_length=255)),
                ('attachment_2', models.FileField(blank=True, help_text='Additional document', null=True, upload_to='payroll/attachments/%Y/%m/')),
                ('attachment_2_name', models.CharField(blank=True, default='', help_text='Display name for attachment 2', max_length=255)),
                ('attachment_3', models.FileField(blank=True, help_text='Additional document', null=True, upload_to='payroll/attachments/%Y/%m/')),
                ('attachment_3_name', models.CharField(blank=True, default='', help_text='Display name for attachment 3', max_length=255)),
                ('attachment_4', models.FileField(blank=True, help_text='Additional document', null=True, upload_to='payroll/attachments/%Y/%m/')),
                ('attachment_4_name', models.CharField(blank=True, default='', help_text='Display name for attachment 4', max_length=255)),
                ('attachment_5', models.FileField(blank=True, help_text='Additional document', null=True, upload_to='payroll/attachments/%Y/%m/')),
                ('attachment_5_name', models.CharField(blank=True, default='', help_text='Display name for attachment 5', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(limit_choices_to={'profile__role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Payroll',
                'verbose_name_plural': 'Staff Payrolls',
                'ordering': ['-year', '-month', 'staff__username'],
                'indexes': [models.Index(fields=['payroll_reference'], name='eduweb_staf_payroll_a1cb8b_idx'), models.Index(fields=['staff', 'month', 'year'], name='eduweb_staf_staff_i_b13f31_idx'), models.Index(fields=['payment_status'], name='eduweb_staf_payment_52d85e_idx')],
                'unique_together': {('staff', 'month', 'year')},
            },
        ),
    ]
