# Generated by Django 5.0.1 on 2026-02-11 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0006_lesson_video_file_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='application_fee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='eduweb.course'),
        ),
    ]
