# Generated by Django 5.0.1 on 2026-01-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0006_courseapplication_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='graduation_year',
            field=models.DateField(),
        ),
    ]
