# Generated by Django 5.0.1 on 2026-01-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0007_alter_courseapplication_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('IN', 'India'), ('CN', 'China'), ('NG', 'Nigeria'), ('BR', 'Brazil'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='program',
            field=models.CharField(choices=[('business', 'Business Administration (MBA)'), ('computer-science', 'Computer Science'), ('data-science', 'Data Science'), ('engineering', 'Engineering'), ('health-sciences', 'Health Sciences'), ('psychology', 'Psychology'), ('economics', 'Economics'), ('law', 'Law'), ('arts', 'Arts & Humanities')], max_length=50),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('website', 'University Website'), ('search-engine', 'Search Engine (Google, etc.)'), ('social-media', 'Social Media'), ('friend-family', 'Friend or Family'), ('education-fair', 'Education Fair'), ('school-counselor', 'School Counselor'), ('alumni', 'MIU Alumni'), ('other', 'Other')], max_length=100),
        ),
    ]
