# Generated by Django 5.0.1 on 2026-02-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0007_courseapplication_application_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseapplication',
            name='application_fee',
        ),
    ]
