# Generated by Django 5.2.4 on 2026-02-12 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0007_staffpayroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpayroll',
            name='staff',
            field=models.ForeignKey(help_text='Select staff member (non-students only)', limit_choices_to={'profile__role__in': ['instructor', 'support', 'admin', 'content_manager', 'finance']}, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL),
        ),
    ]
