# Generated by Django 6.0.2 on 2026-03-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0007_userprofile_password_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full institution name', max_length=300)),
                ('category', models.CharField(choices=[('partner', 'Partner'), ('affiliation', 'Affiliation'), ('accreditation', 'Accreditation')], default='partner', max_length=20)),
                ('location', models.CharField(blank=True, help_text="e.g. 'New Jersey, USA'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
            ],
            options={
                'verbose_name': 'Institution Partner / Affiliation',
                'verbose_name_plural': 'Institution Partners & Affiliations',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
