# Generated by Django 5.0.1 on 2026-01-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0007_alter_courseapplication_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='graduation_year',
            field=models.TextField(),
        ),
    ]
