# Generated by Django 6.0.2 on 2026-03-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0007_alter_listofcountry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('admin_board', 'Administrative / Management Board'), ('academic_board', 'Academic Board'), ('advisorate_board', 'Advisorate Board'), ('staff', 'Staff')], db_index=True, max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='institution/members/')),
                ('bio', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Institution Member',
                'verbose_name_plural': 'Institution Members',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('school_short_name', models.CharField(blank=True, max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logos/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='site/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicons/')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site/og/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_primary', models.CharField(blank=True, max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('phone_ng_primary', models.CharField(blank=True, max_length=30)),
                ('phone_ng_secondary', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('address_usa', models.TextField(blank=True)),
                ('address_nigeria', models.TextField(blank=True)),
                ('office_hours_weekday', models.CharField(blank=True, max_length=100)),
                ('office_hours_saturday', models.CharField(blank=True, max_length=100)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('stat_years', models.CharField(blank=True, max_length=20)),
                ('stat_faculties', models.CharField(blank=True, max_length=20)),
                ('stat_campuses', models.CharField(blank=True, max_length=20)),
                ('stat_tuition', models.CharField(blank=True, default='0', max_length=20)),
                ('about_intro_1', models.TextField(blank=True)),
                ('about_intro_2', models.TextField(blank=True)),
                ('mission_text', models.TextField(blank=True)),
                ('vision_text', models.TextField(blank=True)),
                ('core_values_text', models.TextField(blank=True)),
                ('accreditation_1', models.CharField(blank=True, max_length=200)),
                ('accreditation_2', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog/authors/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_faculty_label',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_photo',
            field=models.ImageField(blank=True, null=True, upload_to='faculties/deans/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='dean_role',
            field=models.CharField(blank=True, default='Dean', max_length=100),
        ),
    ]
