# Generated by Django 6.0.2 on 2026-03-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0008_institutionmember_siteconfig_blogpost_author_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='core_values_text',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
