# Generated by Django 6.0.2 on 2026-03-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0008_institutionpartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionpartner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Partner logo image (PNG/SVG recommended, transparent background)', null=True, upload_to='partners/logos/'),
        ),
    ]
