# Generated by Django 6.0.2 on 2026-02-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0008_alter_staffpayroll_staff'),
        ('eduweb', '0008_remove_courseapplication_application_fee'),
    ]

    operations = [
    ]
