# Generated by Django 5.0.1 on 2026-01-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0008_alter_courseapplication_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='payment_status',
            field=models.TextField(default='pending'),
        ),
    ]
