# Generated by Django 6.0.2 on 2026-03-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0009_siteconfig_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='campus_map_address',
            field=models.CharField(blank=True, help_text='Address shown on the map overlay card', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='campus_map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='promo_video_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL for the about-section iframe on index page'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat_countries_count',
            field=models.IntegerField(blank=True, default=120, help_text='Countries represented (about page)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat_employment_rate',
            field=models.IntegerField(blank=True, default=95, help_text='Graduate employment % (about page)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat_programs_count',
            field=models.IntegerField(blank=True, default=50, help_text='Number of programs (about page)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat_years_count',
            field=models.IntegerField(blank=True, default=30, help_text='Years of excellence (about page animated counter)'),
        ),
    ]
