# Generated by Django 5.0.1 on 2026-02-20 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0009_merge_20260219_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='eduweb.faculty'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (e.g., Electrical Engineering)', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Department code (e.g., EEE)', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='eduweb.faculty')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('faculty', 'code')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='eduweb.department'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Program name (e.g., BSc Electrical Engineering)', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Program code (e.g., BSC-EEE)', max_length=30)),
                ('degree_level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('masters', 'Masters'), ('phd', 'PhD')], max_length=50)),
                ('duration_years', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='eduweb.department')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='eduweb.program'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to='eduweb.program'),
        ),
    ]
