# Generated by Django 5.2.4 on 2026-01-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0010_courseapplication_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
