# Generated by Django 5.0.1 on 2026-02-20 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0010_userprofile_faculty_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRequiredPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(help_text='Purpose of the payment (e.g., School Fees, Library Fees)', max_length=255)),
                ('who_to_pay', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('applicant', 'Applicant'), ('other', 'Other')], default='student', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid', max_digits=10)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility of this payment')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_payments', to='eduweb.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_payments', to='eduweb.faculty')),
            ],
            options={
                'verbose_name': 'Required Payment',
                'verbose_name_plural': 'All Required Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
