# Generated by Django 6.0.2 on 2026-03-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0010_alter_certificate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
