# Generated by Django 6.0.2 on 2026-03-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0010_siteconfig_campus_map_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_exchange_programs',
            field=models.CharField(blank=True, default='40+', help_text='Exchange programs count on about page', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_languages_spoken',
            field=models.CharField(blank=True, default='15+', help_text='Languages spoken count on about page', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_partner_institutions',
            field=models.CharField(blank=True, default='200+', help_text='Partner institutions count on about page', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_years_founded',
            field=models.CharField(blank=True, default='1995', help_text='Founding year used on about page text', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='accreditation_3',
            field=models.CharField(blank=True, help_text='Third accreditation line (about page)', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='accreditation_4',
            field=models.CharField(blank=True, help_text='Fourth accreditation line (about page)', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='copyright_year',
            field=models.CharField(blank=True, default='2025', help_text='Year shown in footer copyright line', max_length=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_tagline',
            field=models.TextField(blank=True, default='Empowering global education since 1995 with innovative learning experiences and world-class faculty.', help_text='Short paragraph under logo in footer'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_badge_text',
            field=models.CharField(blank=True, default='Melchisedec International University', help_text='Badge text above hero heading', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_heading',
            field=models.CharField(blank=True, default='Welcome to MIU', help_text='Main hero h1 text (first line)', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_subheading',
            field=models.CharField(blank=True, default='Global Institution of Excellence in Learning and Academics', help_text='Subtitle paragraph below hero heading', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_tagline',
            field=models.CharField(blank=True, default='The Best Learning Institution', help_text='Subtitle line below badge in hero', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='index_about_para_1',
            field=models.TextField(blank=True, help_text='First paragraph in index about section'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='index_about_para_2',
            field=models.TextField(blank=True, help_text='Second paragraph in index about section'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat_countries_label',
            field=models.CharField(blank=True, default='120+', help_text="Countries stat card value e.g. '120+'", max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat_employment_label',
            field=models.CharField(blank=True, default='95%', help_text="Employment stat card e.g. '95%'", max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat_programs_label',
            field=models.CharField(blank=True, default='50+', help_text="Programs stat card e.g. '50+'", max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='stat_students',
            field=models.CharField(blank=True, default='25,000+', help_text="Students stat card value e.g. '25,000+'", max_length=30),
        ),
    ]
