# Generated by Django 5.0.1 on 2026-01-18 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0011_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 18, 0, 40, 22, 911895, tzinfo=datetime.timezone.utc)),
        ),
    ]
