# Generated by Django 5.2.4 on 2026-01-19 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0011_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Faculty name (e.g., Faculty of Business)', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly name', max_length=200, unique=True)),
                ('code', models.CharField(help_text='Faculty code (e.g., BUS, ENG)', max_length=20, unique=True)),
                ('icon', models.CharField(default='graduation-cap', help_text='Lucide icon name', max_length=50)),
                ('color_primary', models.CharField(default='orange', help_text='Primary color (e.g., orange, blue)', max_length=20)),
                ('color_secondary', models.CharField(default='amber', help_text='Secondary color', max_length=20)),
                ('tagline', models.CharField(help_text='Short tagline for hero section', max_length=200)),
                ('description', models.TextField(help_text='Main description of the faculty')),
                ('mission', models.TextField(blank=True, help_text='Faculty mission statement')),
                ('vision', models.TextField(blank=True, help_text='Faculty vision statement')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='faculties/heroes/')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='faculties/about/')),
                ('student_count', models.IntegerField(default=0, help_text='Number of students')),
                ('placement_rate', models.IntegerField(default=0, help_text='Career placement rate (0-100)')),
                ('partner_count', models.IntegerField(default=0, help_text='Number of corporate partners')),
                ('international_faculty', models.IntegerField(default=0, help_text='International faculty percentage (0-100)')),
                ('accreditation', models.TextField(blank=True, help_text='Accreditation details')),
                ('special_features', models.JSONField(blank=True, default=list, help_text='List of special features')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in navigation menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name (e.g., Business Administration)', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Course code (e.g., BUS101)', max_length=20, unique=True)),
                ('icon', models.CharField(default='book-open', help_text='Lucide icon name', max_length=50)),
                ('color_primary', models.CharField(default='blue', help_text='Primary color', max_length=20)),
                ('color_secondary', models.CharField(default='cyan', help_text='Secondary color', max_length=20)),
                ('degree_levels', models.JSONField(default=list, help_text='Available degree levels (BSc, MSc, PhD)')),
                ('study_modes', models.JSONField(default=list, help_text='Available study modes')),
                ('duration_years', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('credits_required', models.IntegerField(default=120)),
                ('tagline', models.CharField(help_text='Short tagline', max_length=200)),
                ('overview', models.TextField(help_text='Program overview')),
                ('description', models.TextField(help_text='Detailed description')),
                ('learning_outcomes', models.JSONField(default=list, help_text='List of learning outcomes')),
                ('career_paths', models.JSONField(default=list, help_text='List of career paths')),
                ('core_courses', models.JSONField(default=list, help_text='Core courses with descriptions')),
                ('specialization_tracks', models.JSONField(default=list, help_text='Specialization options')),
                ('undergraduate_requirements', models.JSONField(default=list, help_text='Undergrad admission requirements')),
                ('graduate_requirements', models.JSONField(default=list, help_text='Graduate admission requirements')),
                ('avg_starting_salary', models.CharField(blank=True, help_text='e.g., $125k', max_length=50)),
                ('job_placement_rate', models.IntegerField(default=0, help_text='Placement rate (0-100)')),
                ('intake_periods', models.JSONField(default=list, help_text='Available intake periods')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='courses/heroes/')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='eduweb.faculty')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['faculty', 'display_order', 'name'],
            },
        ),
    ]
