# Generated by Django 6.0.2 on 2026-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0011_siteconfig_about_exchange_programs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.TextField(blank=True, help_text='Paste the full embed iframe code from YouTube, Vimeo, etc.', null=True),
        ),
    ]
