# Generated by Django 6.0.2 on 2026-03-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0011_userprofile_last_activity_userprofile_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='session_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_session_key',
            field=models.CharField(blank=True, default='', help_text='Django session key of the current active session.', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_logged_in',
            field=models.BooleanField(default=False, help_text='True while a session is active for this user.'),
        ),
    ]
