# Generated by Django 5.2.4 on 2026-01-20 00:03

import django.db.models.deletion
import django.utils.timezone
import eduweb.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0012_faculty_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Student Life)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.CharField(default='folder', help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(default='blue', help_text='Color theme (e.g., blue, green)', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order in category list')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='avg_starting_salary',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='career_paths',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Course code', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='color_primary',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='color_secondary',
            field=models.CharField(default='cyan', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='core_courses',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree_levels',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='graduate_requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='intake_periods',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='job_placement_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_outcomes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Course name', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization_tracks',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='study_modes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='tagline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='undergraduate_requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='referral_source',
            field=models.CharField(blank=True, choices=[('website', 'University Website'), ('search-engine', 'Search Engine'), ('social-media', 'Social Media'), ('friend-family', 'Friend or Family'), ('education-fair', 'Education Fair'), ('school-counselor', 'School Counselor'), ('alumni', 'MIU Alumni'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='color_primary',
            field=models.CharField(default='orange', help_text='Primary color', max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='international_faculty',
            field=models.IntegerField(default=0, help_text='International faculty percentage'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly title', max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle/excerpt', max_length=200)),
                ('excerpt', models.TextField(help_text='Short summary (max 500 chars)', max_length=500)),
                ('content', models.TextField(help_text='Full blog post content (supports HTML)')),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of tags (e.g., ['technology', 'innovation'])")),
                ('author_name', models.CharField(help_text='Display name (overrides user)', max_length=100)),
                ('author_title', models.CharField(blank=True, help_text="e.g., 'Communications Director'", max_length=100)),
                ('featured_image', models.ImageField(blank=True, help_text='Main post image (recommended: 1200x630px)', null=True, upload_to=eduweb.models.blog_image_upload_path)),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('views_count', models.IntegerField(default=0, help_text='Number of views')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='eduweb.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-publish_date', '-created_at'],
                'indexes': [models.Index(fields=['-publish_date', 'status'], name='eduweb_blog_publish_acc07e_idx'), models.Index(fields=['slug'], name='eduweb_blog_slug_cacd18_idx')],
            },
        ),
    ]
