# Generated by Django 6.0.2 on 2026-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0012_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='campus_map_embed_url',
            field=models.TextField(blank=True, help_text='Paste the full <iframe> embed code from Google Maps'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='promo_video_url',
            field=models.TextField(blank=True, help_text='Paste the full <iframe> embed code from YouTube, Vimeo, etc.'),
        ),
    ]
