# Generated by Django 6.0.3 on 2026-03-18 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0013_alter_siteconfig_campus_map_embed_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], max_length=30)),
                ('payment_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=255)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_metadata', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='eduweb.allrequiredpayments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Student Fee Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_reference'], name='eduweb_stud_payment_42c65e_idx'), models.Index(fields=['status'], name='eduweb_stud_status_a01c3b_idx')],
            },
        ),
    ]
