# Generated by Django 5.0.1 on 2026-01-18 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0013_alter_courseapplicationfile_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplicationfile',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseapplicationfile',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseapplicationfile',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='courseapplicationfile',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 18, 11, 11, 34, 455802, tzinfo=datetime.timezone.utc)),
        ),
    ]
