# Generated by Django 6.0.2 on 2026-04-01 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0013_coursegrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmscourse',
            name='academic_course',
            field=models.ForeignKey(blank=True, help_text='The academic course unit this LMS content delivers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='eduweb.course'),
        ),
    ]
