# Generated by Django 6.0.3 on 2026-03-18 18:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0014_studentfeepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentFeePayment',
            new_name='FeePayment',
        ),
        migrations.RenameIndex(
            model_name='feepayment',
            new_name='eduweb_feep_payment_9c4347_idx',
            old_name='eduweb_stud_payment_42c65e_idx',
        ),
        migrations.RenameIndex(
            model_name='feepayment',
            new_name='eduweb_feep_status_f11d45_idx',
            old_name='eduweb_stud_status_a01c3b_idx',
        ),
    ]
