# Generated by Django 6.0.2 on 2026-04-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0014_lmscourse_academic_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='allrequiredpayments',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code e.g. USD, GBP, EUR', max_length=3),
        ),
    ]
