# Generated by Django 5.0.1 on 2026-01-20 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0014_courseapplicationfile_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 19, 39, 35, 168093, tzinfo=datetime.timezone.utc)),
        ),
    ]
