# Generated by Django 5.0.1 on 2026-01-22 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0015_alter_courseapplicationfile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 22, 19, 20, 54, 559846, tzinfo=datetime.timezone.utc)),
        ),
    ]
