# Generated by Django 6.0.2 on 2026-04-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0015_allrequiredpayments_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpayroll',
            name='currency',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code e.g. USD, GBP, EUR', max_length=3),
        ),
    ]
