# Generated by Django 6.0.2 on 2026-04-01 20:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0016_staffpayroll_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allrequiredpayments',
            unique_together={('program', 'academic_session', 'purpose', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='feepayment',
            unique_together={('user', 'fee')},
        ),
    ]
