# Generated by Django 5.0.1 on 2026-01-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0013_blogcategory_alter_course_avg_starting_salary_and_more'),
        ('eduweb', '0016_alter_courseapplication_date_of_birth_and_more'),
    ]

    operations = [
    ]
