# Generated by Django 6.0.2 on 2026-04-24 12:52

import django.core.validators
import django.db.models.deletion
import eduweb.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0017_alter_allrequiredpayments_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='e.g. first, second, fall', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dropped', 'Dropped')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('dropped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Course Registration',
                'verbose_name_plural': 'Course Registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('reference_code', models.CharField(blank=True, db_index=True, help_text='Auto-generated on save. Printed on timetables, e.g. EX-2025-4F2A.', max_length=40, unique=True)),
                ('title', models.CharField(help_text="e.g. 'CSC301 — Data Structures End-of-Semester Exam 2025'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Internal description; not shown to students.')),
                ('exam_type', models.CharField(choices=[('ca', 'Continuous Assessment'), ('mid_semester', 'Mid-Semester Exam'), ('end_of_semester', 'End-of-Semester Exam'), ('supplementary', 'Supplementary Exam'), ('resit', 'Resit / Make-up Exam'), ('practical', 'Practical Exam'), ('oral', 'Oral / Viva Exam')], default='end_of_semester', max_length=30)),
                ('mode', models.CharField(choices=[('in_person', 'In-Person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='in_person', max_length=20)),
                ('exam_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(help_text='Exact exam start. The instruction-page countdown counts to this.')),
                ('end_time', models.TimeField(help_text='Exam end time. Server fires auto-submit at this time.')),
                ('instruction_window_minutes', models.PositiveIntegerField(default=10, help_text='Minutes before start_time the instruction page unlocks. The countdown reads down to start_time; questions auto-unlock at zero.')),
                ('venue', models.CharField(blank=True, help_text="Hall name, room number, or 'Online'.", max_length=200)),
                ('hall_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_candidates', models.PositiveIntegerField(blank=True, null=True)),
                ('eligible_levels', models.CharField(blank=True, help_text="Comma-separated student levels eligible, e.g. '200,300'.", max_length=100)),
                ('questions_per_student', models.PositiveIntegerField(blank=True, help_text='Questions served to each student. Blank = give all active questions.', null=True)),
                ('difficulty_mix', models.JSONField(blank=True, default=dict, help_text='e.g. {"easy": 40, "medium": 40, "hard": 20}. Empty = ignore difficulty.')),
                ('shuffle_questions', models.BooleanField(default=True, help_text='Serve questions in a different order to each student.')),
                ('shuffle_options', models.BooleanField(default=True, help_text='Shuffle MCQ answer options independently per student.')),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, help_text='Auto-summed from active pool questions, or set manually.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('pass_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('show_result_immediately', models.BooleanField(default=False, help_text='Show score to student immediately after auto-graded submission.')),
                ('show_answers_after', models.DateTimeField(blank=True, help_text='When correct answers become visible to students.', null=True)),
                ('question_import_file', models.FileField(blank=True, help_text='Upload .docx or .xlsx. Background task parses into ExamQuestion rows.', null=True, upload_to=eduweb.models.upload_path('exam_question_imports'))),
                ('import_status', models.CharField(choices=[('none', 'No import'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='none', max_length=20)),
                ('import_error_log', models.TextField(blank=True, help_text='Rows that failed parsing — shown to the instructor.')),
                ('timetable_file', models.FileField(blank=True, null=True, upload_to=eduweb.models.upload_path('exam_timetables'))),
                ('seating_plan_file', models.FileField(blank=True, null=True, upload_to=eduweb.models.upload_path('exam_seating_plans'))),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('submission_count', models.PositiveIntegerField(default=0, help_text='Increments on each instructor submission — tracks revision cycles.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('visible_from_override', models.DateTimeField(blank=True, help_text='Optional. Override when students can first see this exam. Leave blank to default to exam_start_datetime.', null=True)),
                ('visible_until_override', models.DateTimeField(blank=True, help_text='Optional. Override when this exam disappears from student view. Leave blank to default to exam_end_datetime.', null=True)),
                ('clash_group', models.CharField(blank=True, db_index=True, max_length=80)),
                ('has_clash', models.BooleanField(default=False)),
                ('clash_notes', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Shown to students on the instruction page during the countdown.')),
                ('special_instructions', models.TextField(blank=True, help_text="Shown on the timetable listing (e.g. 'Bring your matric card').")),
                ('internal_notes', models.TextField(blank=True, help_text='Staff-only — never visible to students.')),
                ('has_accommodations', models.BooleanField(default=False)),
                ('accommodation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice (single answer)'), ('multi_select', 'Multiple Choice (multiple answers)'), ('true_false', 'True / False'), ('short_answer', 'Short Answer'), ('essay', 'Essay / Long Answer')], default='mcq', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, help_text='Optional diagram or figure for the question.', null=True, upload_to=eduweb.models.upload_path('exam_question_images'))),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown to students after answers are released.')),
                ('options', models.JSONField(blank=True, default=list, help_text='Array of answer options. Each: {"id": "opt-uuid", "text": "...", "is_correct": bool}. Empty for short_answer / essay. SECURITY: strip is_correct before sending to frontend.')),
                ('accepted_answers', models.JSONField(blank=True, default=list, help_text='For short_answer only. Exact-match strings for auto-grading.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Default display order within the exam (overridden by shuffle).')),
                ('tags', models.JSONField(blank=True, default=list, help_text='e.g. ["chapter-3", "sorting", "complexity"]')),
                ('source_reference', models.CharField(blank=True, help_text='e.g. "2019 Past Question Q4" or "Imported via Q-Bank"', max_length=255)),
                ('year_first_used', models.PositiveIntegerField(blank=True, help_text='Year this question was first used — helps avoid recent repeats.', null=True)),
                ('imported_from_file', models.CharField(blank=True, help_text='Original filename this question was parsed from, if imported.', max_length=255)),
                ('import_row_number', models.PositiveIntegerField(blank=True, help_text='Row/paragraph number in import file — for parse-error tracing.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive questions are excluded from student draws.')),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
                'ordering': ['exam', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, help_text='Rejection reason, approval comment, cancellation note, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exam Status Log',
                'verbose_name_plural': 'Exam Status Logs',
                'ordering': ['-created_at'],
            },
            bases=(eduweb.models.ImmutableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StudentExamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('assigned_question_ids', models.JSONField(default=list, help_text='Ordered list of ExamQuestion PKs drawn for this student. Written once.')),
                ('assigned_options_order', models.JSONField(default=dict, help_text='Maps question PK → shuffled option ID list as shown to this student. Written once.')),
                ('answers', models.JSONField(default=dict, help_text='Student answers keyed by question PK. Updated incrementally by auto-save.')),
                ('question_scores', models.JSONField(default=dict, help_text='Per-question grading breakdown. Each entry: {"marks_awarded": N|null, "max_marks": N, "is_correct": bool|null}. null marks_awarded = pending manual grading.')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Null until fully graded.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('score_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='(total_score / total_marks) × 100. Computed on grading completion.', max_digits=5, null=True)),
                ('passed', models.BooleanField(help_text='Null until graded. True if total_score >= Exam.pass_mark.', null=True)),
                ('overall_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('pending_manual_count', models.PositiveIntegerField(default=0, help_text='Questions still awaiting manual grading.')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('instructions', 'Reading Instructions'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('absent', 'Absent')], db_index=True, default='not_started', max_length=20)),
                ('instructions_opened_at', models.DateTimeField(blank=True, null=True)),
                ('exam_started_at', models.DateTimeField(blank=True, help_text='When questions were revealed (countdown hit 0).', null=True)),
                ('last_autosave_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_submitted', models.BooleanField(default=False, help_text='True if submission was triggered by the server timer.')),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, help_text='Seconds from exam_started_at to submitted_at.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tab_switch_count', models.PositiveIntegerField(default=0)),
                ('invigilator_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Exam Response',
                'verbose_name_plural': 'Student Exam Responses',
                'ordering': ['exam', 'student'],
            },
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='eduweb_cour_academi_789293_idx',
        ),
        migrations.RemoveIndex(
            model_name='lmscourse',
            name='eduweb_lmsc_categor_0b0e1d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='coursegrade',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='first_semester_end',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='first_semester_start',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='second_semester_end',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='second_semester_start',
        ),
        migrations.AddField(
            model_name='academicsession',
            name='override_current_term',
            field=models.CharField(blank=True, choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('third', 'Third Semester / Harmattan'), ('annual', 'Annual'), ('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], help_text='Admin override: force the system to report this term as current', max_length=20),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='term_dates',
            field=models.JSONField(default=list, help_text='List of term windows. Each item: {"term": "first|second|third|fall|spring|summer", "start": "YYYY-MM-DD", "end": "YYYY-MM-DD"}'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Courses that must be passed before registering for this one', related_name='prerequisite_for', to='eduweb.course'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='lms_course',
            field=models.ForeignKey(blank=True, help_text='The LMS delivery this result is linked to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_grades', to='eduweb.lmscourse'),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='result_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('withheld', 'Withheld')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='coursegrade',
            name='term',
            field=models.CharField(blank=True, help_text='Term this grade belongs to', max_length=20),
        ),
        migrations.AddField(
            model_name='lmscourse',
            name='lecturer',
            field=models.ForeignKey(blank=True, help_text='Assigned academic lecturer for this delivery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses_as_lecturer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lmscourse',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Academic session this delivery runs in. Null = self-paced standalone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='eduweb.academicsession'),
        ),
        migrations.AddField(
            model_name='lmscourse',
            name='term',
            field=models.CharField(blank=True, choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('third', 'Third Semester'), ('annual', 'Annual'), ('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], help_text='Term within the session. Auto-derived from session.get_current_term() if blank.', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='max_credits_per_semester',
            field=models.PositiveIntegerField(default=24, help_text='Maximum total credit units a student can register in ONE semester for this program', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='admission_session',
            field=models.ForeignKey(blank=True, help_text='Session in which the student was admitted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='eduweb.academicsession'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='progression_status',
            field=models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('repeated', 'Repeating Level'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current year of study. Level = year × 100 (e.g. year 1 = 100L).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='allrequiredpayments',
            name='semester',
            field=models.CharField(blank=True, choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('third', 'Third Semester'), ('annual', 'Annual'), ('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], default='annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('access', 'Access'), ('export', 'Export'), ('permission_change', 'Permission Change'), ('course_access', 'Course Access'), ('assignment_submit', 'Assignment Submitted'), ('exam_start', 'Exam Started'), ('exam_finish', 'Exam Finished'), ('level_progression', 'Level Progression'), ('registration', 'Course Registration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='year_of_study',
            field=models.IntegerField(help_text='Which year of the program this course is taught in (e.g., 1, 2, 3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='lmscourse',
            name='academic_course',
            field=models.ForeignKey(blank=True, help_text='The academic course unit this LMS content delivers. Null = standalone LMS course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='eduweb.course'),
        ),
        migrations.AlterField(
            model_name='lmscourse',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='lmscourse',
            name='difficulty_level',
            field=models.CharField(choices=[('1', '100 Level'), ('2', '200 Level'), ('3', '300 Level'), ('4', '400 Level'), ('5', '500 Level'), ('6', '600 Level'), ('7', '700 Level'), ('8', '800 Level')], default='1', max_length=5, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='lmscourse',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Estimated duration in hours', max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='coursegrade',
            unique_together={('student', 'course', 'session', 'term')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action', '-timestamp'], name='eduweb_audi_user_id_385882_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type', 'year_of_study'], name='eduweb_cour_course__493bef_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['student', 'session'], name='eduweb_cour_student_f3fe8b_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegrade',
            index=models.Index(fields=['result_status'], name='eduweb_cour_result__aa1e44_idx'),
        ),
        migrations.AddIndex(
            model_name='lmscourse',
            index=models.Index(fields=['session', 'term'], name='eduweb_lmsc_session_b430fb_idx'),
        ),
        migrations.AddIndex(
            model_name='lmscourse',
            index=models.Index(fields=['academic_course', 'session'], name='eduweb_lmsc_academi_75e919_idx'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='eduweb.course'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='eduweb.academicsession'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='eduweb.academicsession'),
        ),
        migrations.AddField(
            model_name='exam',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(help_text='LMS course this exam belongs to. This may optionally be linked to an academic course via LMSCourse.', on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='eduweb.lmscourse'),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Denormalised from Course for fast timetable filtering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='eduweb.department'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_as_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='invigilators',
            field=models.ManyToManyField(blank=True, related_name='exams_as_invigilator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_questions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='eduweb.exam'),
        ),
        migrations.AddField(
            model_name='examstatuslog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examstatuslog',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='eduweb.exam'),
        ),
        migrations.AddField(
            model_name='studentexamresponse',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_responses', to='eduweb.exam'),
        ),
        migrations.AddField(
            model_name='studentexamresponse',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_responses_graded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentexamresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='course',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='category',
        ),
        migrations.AddIndex(
            model_name='courseregistration',
            index=models.Index(fields=['student', 'session', 'term'], name='eduweb_cour_student_3e4b15_idx'),
        ),
        migrations.AddIndex(
            model_name='courseregistration',
            index=models.Index(fields=['course', 'session'], name='eduweb_cour_course__42e35a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together={('student', 'course', 'session', 'term')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_date', 'status'], name='eduweb_exam_exam_da_f62253_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_session', 'exam_date'], name='eduweb_exam_academi_389c35_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'academic_session'], name='eduweb_exam_course__748b29_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course', 'academic_session', 'exam_type'), name='unique_exam_course_session_type'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='exam_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'difficulty', 'is_active'], name='eduweb_exam_exam_id_47ece1_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'order'], name='eduweb_exam_exam_id_ef097d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamresponse',
            index=models.Index(fields=['exam', 'status'], name='eduweb_stud_exam_id_a0d11e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamresponse',
            index=models.Index(fields=['student', 'status'], name='eduweb_stud_student_818d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamresponse',
            index=models.Index(fields=['exam', 'total_score'], name='eduweb_stud_exam_id_62e7fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentexamresponse',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_student_exam_response'),
        ),
    ]
