# Generated by Django 5.0.1 on 2026-01-23 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0017_merge_20260122_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=255)),
                ('degree_level', models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('masters', 'Masters'), ('phd', 'PhD')], max_length=50)),
                ('study_mode', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('online', 'Online'), ('blended', 'Blended')], max_length=50)),
                ('intake', models.CharField(choices=[('january', 'January'), ('may', 'May'), ('september', 'September'), ('october', 'October')], max_length=50)),
                ('application_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prospective Course',
                'verbose_name_plural': 'Prospective Courses',
                'ordering': ['program'],
            },
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 17, 50, 23, 758946, tzinfo=datetime.timezone.utc)),
        ),
    ]
