# Generated by Django 5.0.1 on 2026-01-23 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0018_prospectivecourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount the applicant has paid so far', max_digits=10),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='application_cost',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 20, 17, 56, 283741, tzinfo=datetime.timezone.utc)),
        ),
    ]
