# Generated by Django 6.0.2 on 2026-04-30 12:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0018_courseregistration_exam_examquestion_examstatuslog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['year_of_study', 'semester', 'name'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['start_datetime'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['exam', 'created_at'], 'verbose_name': 'Exam Question', 'verbose_name_plural': 'Exam Questions'},
        ),
        migrations.RemoveConstraint(
            model_name='exam',
            name='unique_exam_course_session_type',
        ),
        migrations.RemoveConstraint(
            model_name='exam',
            name='exam_end_after_start',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='eduweb_exam_exam_da_f62253_idx',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='eduweb_exam_academi_389c35_idx',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='eduweb_exam_course__748b29_idx',
        ),
        migrations.RemoveIndex(
            model_name='examquestion',
            name='eduweb_exam_exam_id_47ece1_idx',
        ),
        migrations.RemoveIndex(
            model_name='examquestion',
            name='eduweb_exam_exam_id_ef097d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='allrequiredpayments',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='override_current_term',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='registration_end',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='registration_start',
        ),
        migrations.RemoveField(
            model_name='course',
            name='color_primary',
        ),
        migrations.RemoveField(
            model_name='course',
            name='color_secondary',
        ),
        migrations.RemoveField(
            model_name='course',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='course',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='courseapplication',
            name='intake',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='certificate_fee',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='certificate_template',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='enrollment_end_date',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='enrollment_start_date',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='has_certificate',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='instructor_bio',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='language',
        ),
        migrations.RemoveField(
            model_name='lmscourse',
            name='max_students',
        ),
        migrations.AddField(
            model_name='allrequiredpayments',
            name='level',
            field=models.IntegerField(blank=True, choices=[(100, 'Level 100'), (200, 'Level 200'), (300, 'Level 300'), (400, 'Level 400'), (500, 'Level 500'), (600, 'Level 600'), (700, 'Level 700'), (800, 'Level 800')], help_text='Student level this fee applies to (100–800). Leave blank to apply to ALL levels.', null=True),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='eduweb.academicsession'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='entry_level',
            field=models.IntegerField(blank=True, help_text='Entry level e.g. 100, 200, 300 etc.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Exam end (date + time). Server fires auto-submit at this moment.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Exact exam start (date + time). The instruction-page countdown counts to this.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(help_text='LMS course this exam belongs to. Academic session, department, and eligible student level are all derived from here — no need to store them separately.', on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='eduweb.lmscourse'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='reference_code',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated on save. e.g. EX-2025-4F2A.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='special_instructions',
            field=models.TextField(blank=True, help_text="Additional notes shown on the exam listing (e.g. 'Have your matric card ready')."),
        ),
        migrations.AlterField(
            model_name='lmscourse',
            name='difficulty_level',
            field=models.IntegerField(choices=[(100, 'Level 100'), (200, 'Level 200'), (300, 'Level 300'), (400, 'Level 400'), (500, 'Level 500'), (600, 'Level 600'), (700, 'Level 700'), (800, 'Level 800')], default=100, verbose_name='Level'),
        ),
        migrations.AlterUniqueTogether(
            name='allrequiredpayments',
            unique_together={('program', 'academic_session', 'purpose', 'semester', 'level')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_datetime', 'status'], name='eduweb_exam_start_d_7f6796_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'start_datetime'], name='eduweb_exam_course__746e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'is_active'], name='eduweb_exam_exam_id_fea488_idx'),
        ),
        migrations.AddIndex(
            model_name='examquestion',
            index=models.Index(fields=['exam', 'created_at'], name='eduweb_exam_exam_id_f9f459_idx'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='exam_end_after_start'),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='accommodation_notes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='clash_group',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='department',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='difficulty_mix',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='eligible_levels',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='expected_candidates',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='hall_capacity',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='has_accommodations',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='has_clash',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='instruction_window_minutes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='invigilators',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='seating_plan_file',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='timetable_file',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='visible_from_override',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='visible_until_override',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='import_row_number',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='order',
        ),
    ]
