# Generated by Django 5.0.1 on 2026-01-23 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0019_courseapplication_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 20, 20, 17, 796206, tzinfo=datetime.timezone.utc)),
        ),
    ]
