# Generated by Django 5.0.1 on 2026-01-23 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0020_alter_courseapplicationfile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='application_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 20, 24, 28, 173329, tzinfo=datetime.timezone.utc)),
        ),
    ]
