# Generated by Django 5.0.1 on 2026-01-23 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0021_alter_courseapplication_application_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='amount_paid1',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount the applicant has paid so far', max_digits=10),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='application_cost1',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 20, 27, 20, 808971, tzinfo=datetime.timezone.utc)),
        ),
    ]
