# Generated by Django 5.0.1 on 2026-01-23 20:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0022_courseapplication_amount_paid1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseapplication',
            name='amount_paid1',
        ),
        migrations.RemoveField(
            model_name='courseapplication',
            name='application_cost1',
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='application_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='eduweb.prospectivecourse'),
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 20, 43, 29, 79423, tzinfo=datetime.timezone.utc)),
        ),
    ]
