# Generated by Django 5.0.1 on 2026-01-23 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0023_remove_courseapplication_amount_paid1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 20, 47, 24, 920305, tzinfo=datetime.timezone.utc)),
        ),
    ]
