# Generated by Django 5.0.1 on 2026-01-23 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0025_alter_courseapplicationfile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 20, 48, 24, 754857, tzinfo=datetime.timezone.utc)),
        ),
    ]
