# Generated by Django 5.0.1 on 2026-01-17 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0011_merge_20260117_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduweb.application'),
        ),
        migrations.RemoveField(
            model_name='applicationpayment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='applicationpayment',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='courseapplicationfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Application_pay',
        ),
        migrations.DeleteModel(
            name='ApplicationPayment',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
