# Generated by Django 5.0.1 on 2026-01-18 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduweb', '0006_vendor_alter_courseapplicationfile_options_and_more'),
        ('eduweb', '0010_courseapplication_decision_and_more'),
    ]

    operations = [
    ]
